# Generated by Django 6.0.2 on 2026-02-27 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('accused_name', models.CharField(blank=True, default='', max_length=255)),
                ('accused_role', models.CharField(blank=True, default='', max_length=255)),
                ('impact_flags', models.JSONField(default=list)),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
            options={
                'db_table': 'complaint_attachments',
            },
        ),
    ]
